#:schema node_modules/wrangler/config-schema.json
name = "twikoo"
main = "src/index.js"
compatibility_flags = ["nodejs_compat"]
compatibility_date = "2024-09-23"

[[d1_databases]]
binding = "DB" # available in your Worker on env.DB
database_name = "twikoo"
database_id = "c251f4c5-2523-4c89-a1a6-558fff7bcfee"

[[r2_buckets]]
binding = "R2"
bucket_name = "twikoo"

[vars]
R2_PUBLIC_URL = "https://twikoo.r2.mingy.org"

[dev]
port = 5000
